### ISSUE TITLE
Daily indexing doesn't appear to be happening

### ISSUE THREAD

**Issue by gcox** [CocoaPods/indexer.cocoapods.org#11]
I submitted two specs 7-8 days ago that are still not showing up in search results on cocoapods.org:
1. JobQueue, [first commit to trunk](https://github.com/CocoaPods/Specs/commit/4e6f5496a654bfe955bbaecb6ed807e76c648d2a)
2. NanoID, [first commit to trunk](https://github.com/CocoaPods/Specs/commit/0d9eb25bbdf6227d6de3ca34c5c19b8d2d9ff574)

**Comment by Haroenv** [comment]
Hmm, you seem to be correct. I'm not sure what the cause is yet :(

**Comment by Haroenv** [comment]
I've investigated and found two issues:

1. when daily indexing stalls, it will not retry (fixed)
2. doing daily indexing uses too much memory, since the packages are too big, and it crashes the server

Now busy investigating a solution for 2 by chunking the query

**Comment by Haroenv** [comment]
It's fixed!

**Comment by gcox** [comment]
Referencing the related commits:
2b4f06a3e018f19b0e1e34c3cb249145168b7266
4605e1de6012f659fa4ace962c75a4a38f2d6f69
